### ISSUE TITLE
`mypy` gives error for `np.ndarray` as container type

### ISSUE THREAD

**Issue by padix-key** [patrick-kidger/jaxtyping#230]
According to the documentation you can use different kinds of containers including `np.ndarray` e.g.
```python
Float[np.ndarray, "..."]
```

However, when running `mypy` it gives:

```
error: Missing type parameters for generic type "ndarray"  [type-arg]
```

Full example:
```python
import numpy as np
from jaxtyping import Float

def func(a: Float[np.ndarray, "..."]) -> None:
    return None
```

I know the FAQ emphasizes the rudimentary support of static type checkers (https://docs.kidger.site/jaxtyping/faq/#is-jaxtyping-compatible-with-static-type-checkers-like-mypypyrightpytype), but it does not state that this case does not work with `mypy`. Hence, I wanted to bring this up.

**Comment by phinate** [comment]
FWIW, you can do 

```python
import numpy.typing as npt
import numpy as np
from jaxtyping import Float32

def func(a: Float32[npt.NDArray[np.float32], "..."]) -> None:
    return None
```

and this will satisfy the `[type-arg]` errors while also making use of the dtype specificity. 

Worth noting that using `Float` will not pick up the fact that the container has the `np.float32` parameter and would not error if you passed in higher precision; strictly, these things are incompatible, so probably some kind of error should be raised. of course it's also annoying to have to specify float32 twice... I'm doing this because I value the check in other scenarios, and I know my precision ahead of time!
