### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by lockwo** [patrick-kidger/jaxtyping#245]
In the FAQ, the complex dtype link is broken: https://posita.github.io/numerary/0.4/whytho/

**Comment by posita** [comment]
I'm pretty sure this can be fixed by updating https://github.com/patrick-kidger/jaxtyping/blob/b3a13eb86acaeab2aacb0cdf79884c4bfe4bc028/docs/faq.md?plain=1#L61 to https://beartype.github.io/numerary/0.4/whytho/ , but please let me know if you're aware of any links to the legacy location, and I'll work to fix them.

**Comment by patrick-kidger** [comment]
Thank you both! I've just pushed an update fixing the broken link (will be picked up automatically in the next hour) so I'm going to close this now.
